#!/usr/bin/env python3
"""scripts/check_generated_sources.py — у производного файла назван его исходник.

Правило 118 каталога: всё, что получено преобразованием, сопровождается
исходником — иначе правила преобразования меняются, а пересобрать нечем, и
производное начинают править руками. Правка руками производного файла хуже
отсутствия файла: она переживает пересборку ровно до следующей и исчезает молча.

Проверяются два встречных факта:

* у файла с шапкой «СГЕНЕРИРОВАНО …» назван генератор, и он **существует**;
* генератор, который такую шапку пишет, **не забыл** её ни в одном месте —
  иначе завтрашний читатель поправит файл руками, не увидев предупреждения.

Область — документация и данные репозитория. Сборки (`dist/`, кэши) сюда не
входят: их исходник — сам репозиторий, и проверять это незачем.

Запуск::

    python scripts/check_generated_sources.py
"""

from __future__ import annotations

import contextlib
import pathlib
import re
import sys

# issue #1394: консоль Windows работает в cp1251/cp866, и печать символов вне
# этой кодировки роняет скрипт `UnicodeEncodeError` прямо в CI-джобе.
for _stream in (sys.stdout, sys.stderr):
    with contextlib.suppress(AttributeError, ValueError, OSError):
        _stream.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[union-attr]

__all__ = ["HEADER_RE", "generated_files", "main", "problems_with_sources"]

_ROOT = pathlib.Path(__file__).parent.parent
_SEARCH = ("docs", ".github", ".rules")
_SUFFIXES = (".md", ".json", ".yml")

#: Шапка производного файла: слово и путь к генератору. Путь обязателен —
#: «сгенерировано» без имени генератора не отвечает на вопрос «чем пересобрать».
HEADER_RE = re.compile(r"(?:СГЕНЕРИРОВАНО|GENERATED)\s+(?P<source>[\w./-]+\.py)", re.IGNORECASE)

_MARKER = re.compile(r"СГЕНЕРИРОВАНО|GENERATED BY|не править руками", re.IGNORECASE)


def generated_files(root: pathlib.Path | None = None) -> list[pathlib.Path]:
    """Файлы, объявившие себя производными (по маркеру в первых строках)."""
    base = root or _ROOT
    found: list[pathlib.Path] = []
    for directory in _SEARCH:
        for path in sorted((base / directory).rglob("*")):
            if path.suffix not in _SUFFIXES or not path.is_file():
                continue
            head = "\n".join(path.read_text(encoding="utf-8").splitlines()[:3])
            if _MARKER.search(head):
                found.append(path)
    return found


def problems_with_sources(root: pathlib.Path | None = None) -> list[str]:
    """Производные файлы, у которых исходник не назван или не существует."""
    base = root or _ROOT
    problems: list[str] = []
    for path in generated_files(base):
        head = "\n".join(path.read_text(encoding="utf-8").splitlines()[:3])
        match = HEADER_RE.search(head)
        relative = path.relative_to(base)
        if match is None:
            problems.append(
                f"{relative}: объявлен производным, но генератор не назван — "
                "пересобрать его нечем, и первую же правку сделают руками"
            )
            continue
        source = base / match.group("source")
        if not source.exists():
            problems.append(
                f"{relative}: назван генератор {match.group('source')}, которого нет — "
                "исходник исчез, а производное осталось"
            )
    return problems


def main() -> int:
    """0 — у каждого производного назван живой исходник; 1 — нет."""
    problems = problems_with_sources()
    if problems:
        print("производное без исходника:", file=sys.stderr)
        for problem in problems:
            print(f"  • {problem}", file=sys.stderr)
        return 1

    print(f"производные файлы называют свой генератор: {len(generated_files())}")
    return 0


if __name__ == "__main__":  # pragma: no cover — точка входа
    raise SystemExit(main())
