#!/usr/bin/env python3
"""scripts/generate_ci_coveragerc.py — per-OS coverage config for CI (issue #294).

Each CI matrix OS job only ever exercises its OWN ``core/sandbox/`` backend
(``_linux.py``/``_macos.py``/``_windows.py``) — the other platforms' backend
files are structurally unreachable on that OS (``SandboxRunner.__init__``
imports each one behind a ``platform.system()`` branch that never matches),
so they permanently read 0% there. That drags down that job's OWN
``pytest --cov-fail-under=85`` gate (``pyproject.toml``) close to the edge —
measured ~86.1% on ubuntu, ~1pp margin — even though the CROSS-OS aggregate
(``coverage-combine`` job, ``--fail-under=90``) already accounts for this
honestly by merging all three jobs' raw ``.coverage`` data.

This script reads the base ``[tool.coverage.run]``/``[tool.coverage.report]``
settings from ``pyproject.toml`` (single source of truth — not duplicated by
hand) and writes ``.coveragerc.ci``, additionally omitting the backend files
that are unreachable on the CURRENT OS only. Used ONLY by the ``test`` job's
per-OS gate (``pytest --cov-config=.coveragerc.ci``); the
``coverage-combine`` job does NOT use this file and keeps reading the plain
``pyproject.toml`` settings, so the cross-OS combined number stays a true
aggregate — no sandbox backend file is ever omitted from every job at once
(issue #294 acceptance criteria: "без двойного исключения одного и того же
кода").

Local ``pytest``/``ruff``/``mypy`` runs are unaffected — this script and
``.coveragerc.ci`` are CI-only; a developer running the project's checklist
locally still sees the full, honest single-OS picture (all sandbox backend
files as always, some naturally at 0% on their machine's OS).

Запуск::

    python scripts/generate_ci_coveragerc.py <Linux|Darwin|Windows>
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

__all__ = ["main", "other_platforms_omit"]

_ROOT = Path(__file__).resolve().parent.parent

# Sandbox backend files that only ever execute on ONE specific OS -- on any
# other OS they are structurally unreachable (SandboxRunner.__init__ never
# imports them there). Keyed by platform.system() value.
_PLATFORM_ONLY_SANDBOX_FILES: dict[str, list[str]] = {
    "Linux": ["src/stepik_grader/core/sandbox/_linux.py"],
    "Darwin": ["src/stepik_grader/core/sandbox/_macos.py"],
    "Windows": ["src/stepik_grader/core/sandbox/_windows.py"],
}

# POSIX-shared code (imported by both _linux.py and _macos.py) -- reachable
# on Linux AND macOS, unreachable on Windows only.
_POSIX_ONLY_SANDBOX_FILES = ["src/stepik_grader/core/sandbox/_posix_common.py"]


def other_platforms_omit(current: str) -> list[str]:
    """Sandbox backend files unreachable on the given ``platform.system()`` value."""
    extra = [
        f for plat, files in _PLATFORM_ONLY_SANDBOX_FILES.items() if plat != current for f in files
    ]
    if current == "Windows":
        extra += _POSIX_ONLY_SANDBOX_FILES
    return extra


def main() -> int:
    """Вернуть 0 при успехе, 1 при неверном usage."""
    if len(sys.argv) != 2 or sys.argv[1] not in _PLATFORM_ONLY_SANDBOX_FILES:
        print(f"usage: {sys.argv[0]} <Linux|Darwin|Windows>", file=sys.stderr)
        return 1
    current = sys.argv[1]

    pyproject = tomllib.loads((_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    run_cfg = pyproject["tool"]["coverage"]["run"]
    report_cfg = pyproject["tool"]["coverage"]["report"]

    omit = [*run_cfg["omit"], *other_platforms_omit(current)]
    source_lines = "\n    ".join(run_cfg["source"])
    omit_lines = "\n    ".join(omit)
    exclude_lines = "\n    ".join(report_cfg["exclude_lines"])

    content = (
        "# Auto-generated by scripts/generate_ci_coveragerc.py (issue #294).\n"
        "# CI-only per-OS override -- do not edit by hand, do not commit.\n"
        "[run]\n"
        "source =\n"
        f"    {source_lines}\n"
        "omit =\n"
        f"    {omit_lines}\n"
        "\n"
        "[report]\n"
        f"fail_under = {report_cfg['fail_under']}\n"
        "exclude_lines =\n"
        f"    {exclude_lines}\n"
    )
    (_ROOT / ".coveragerc.ci").write_text(content, encoding="utf-8")
    print(f"Wrote .coveragerc.ci for {current} (extra omit: {other_platforms_omit(current)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
